// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmGIgbOFFQ9pjilfH1SJD4gHSmiGBrtE',
    appId: '1:248226384043:web:df5523f29dbf0e05c5cfee',
    messagingSenderId: '248226384043',
    projectId: 'heatable-df0b1',
    authDomain: 'heatable-df0b1.firebaseapp.com',
    databaseURL: 'https://heatable-df0b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heatable-df0b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8RKDRysxjWYdyqN7gokr1h_IIJArpgyY',
    appId: '1:248226384043:android:c8c33b6fad529f7bc5cfee',
    messagingSenderId: '248226384043',
    projectId: 'heatable-df0b1',
    databaseURL: 'https://heatable-df0b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heatable-df0b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCccearCIHCRPmE6lPSVuD6IxjweZq9Fac',
    appId: '1:248226384043:ios:639a2f2df419c6a6c5cfee',
    messagingSenderId: '248226384043',
    projectId: 'heatable-df0b1',
    databaseURL: 'https://heatable-df0b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heatable-df0b1.appspot.com',
    iosClientId: '248226384043-494u6cpskliim16alvvhpki8shgfufbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.heatable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCccearCIHCRPmE6lPSVuD6IxjweZq9Fac',
    appId: '1:248226384043:ios:639a2f2df419c6a6c5cfee',
    messagingSenderId: '248226384043',
    projectId: 'heatable-df0b1',
    databaseURL: 'https://heatable-df0b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heatable-df0b1.appspot.com',
    iosClientId: '248226384043-494u6cpskliim16alvvhpki8shgfufbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.heatable',
  );
}
